from distutils.core import setup

setup(
    name='cloudcalc_server',
    version='0.5',
    packages=['', 'lib.python2.7.distutils', 'lib.python2.7.encodings', 'lib.python2.7.site-packages.pip',
              'lib.python2.7.site-packages.pip.vcs', 'lib.python2.7.site-packages.pip._vendor',
              'lib.python2.7.site-packages.pip._vendor.distlib',
              'lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'lib.python2.7.site-packages.pip._vendor.colorama', 'lib.python2.7.site-packages.pip._vendor.html5lib',
              'lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'lib.python2.7.site-packages.pip._vendor.requests',
              'lib.python2.7.site-packages.pip._vendor.requests.packages',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python2.7.site-packages.pip._vendor._markerlib', 'lib.python2.7.site-packages.pip.commands',
              'lib.python2.7.site-packages.pip.backwardcompat', 'lib.python2.7.site-packages.nose',
              'lib.python2.7.site-packages.nose.ext', 'lib.python2.7.site-packages.nose.tools',
              'lib.python2.7.site-packages.nose.sphinx', 'lib.python2.7.site-packages.nose.plugins',
              'lib.python2.7.site-packages.xlrd', 'lib.python2.7.site-packages.flask',
              'lib.python2.7.site-packages.flask.ext', 'lib.python2.7.site-packages.flask.testsuite',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.lib.python2.5.site-packages.site_package',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.path.installed_package',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.flaskext',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.flaskext.oldext_package',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps.admin',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps.frontend',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps.admin',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps.frontend',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.flask_broken',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.config_package_app',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.subdomaintestmodule',
              'lib.python2.7.site-packages.flask.testsuite.test_apps.flask_newext_package',
              'lib.python2.7.site-packages.bcrypt', 'lib.python2.7.site-packages.jinja2',
              'lib.python2.7.site-packages.openpyxl', 'lib.python2.7.site-packages.openpyxl.xml',
              'lib.python2.7.site-packages.openpyxl.cell', 'lib.python2.7.site-packages.openpyxl.chart',
              'lib.python2.7.site-packages.openpyxl.utils', 'lib.python2.7.site-packages.openpyxl.compat',
              'lib.python2.7.site-packages.openpyxl.reader', 'lib.python2.7.site-packages.openpyxl.styles',
              'lib.python2.7.site-packages.openpyxl.writer', 'lib.python2.7.site-packages.openpyxl.drawing',
              'lib.python2.7.site-packages.openpyxl.formula', 'lib.python2.7.site-packages.openpyxl.comments',
              'lib.python2.7.site-packages.openpyxl.workbook', 'lib.python2.7.site-packages.openpyxl.workbook.names',
              'lib.python2.7.site-packages.openpyxl.packaging', 'lib.python2.7.site-packages.openpyxl.worksheet',
              'lib.python2.7.site-packages.openpyxl.chartsheet', 'lib.python2.7.site-packages.openpyxl.formatting',
              'lib.python2.7.site-packages.openpyxl.descriptors', 'lib.python2.7.site-packages.werkzeug',
              'lib.python2.7.site-packages.werkzeug.debug', 'lib.python2.7.site-packages.werkzeug.contrib',
              'lib.python2.7.site-packages._markerlib', 'lib.python2.7.site-packages.et_xmlfile',
              'lib.python2.7.site-packages.et_xmlfile.tests', 'lib.python2.7.site-packages.markupsafe',
              'lib.python2.7.site-packages.setuptools', 'lib.python2.7.site-packages.setuptools.tests',
              'lib.python2.7.site-packages.setuptools.command', 'lib.python2.7.site-packages.sqlalchemy',
              'lib.python2.7.site-packages.sqlalchemy.ext', 'lib.python2.7.site-packages.sqlalchemy.ext.declarative',
              'lib.python2.7.site-packages.sqlalchemy.orm', 'lib.python2.7.site-packages.sqlalchemy.sql',
              'lib.python2.7.site-packages.sqlalchemy.util', 'lib.python2.7.site-packages.sqlalchemy.event',
              'lib.python2.7.site-packages.sqlalchemy.engine', 'lib.python2.7.site-packages.sqlalchemy.testing',
              'lib.python2.7.site-packages.sqlalchemy.testing.suite',
              'lib.python2.7.site-packages.sqlalchemy.testing.plugin',
              'lib.python2.7.site-packages.sqlalchemy.dialects',
              'lib.python2.7.site-packages.sqlalchemy.dialects.mssql',
              'lib.python2.7.site-packages.sqlalchemy.dialects.mysql',
              'lib.python2.7.site-packages.sqlalchemy.dialects.oracle',
              'lib.python2.7.site-packages.sqlalchemy.dialects.sqlite',
              'lib.python2.7.site-packages.sqlalchemy.dialects.sybase',
              'lib.python2.7.site-packages.sqlalchemy.dialects.firebird',
              'lib.python2.7.site-packages.sqlalchemy.dialects.postgresql',
              'lib.python2.7.site-packages.sqlalchemy.databases', 'lib.python2.7.site-packages.sqlalchemy.connectors',
              'lib.python2.7.site-packages.flask_script', 'lib.python2.7.site-packages.flask_sqlalchemy'],
    url='',
    license='Creative Commons',
    author='Slash',
    author_email='dkhorosh@cisco.com',
    description='Server for cloud sizer application'
)
